### ISSUE TITLE
Scott encoding

### ISSUE THREAD

**Issue by suhr** [chatziko/lci#11]
It would be great to have a [Scott encoding](https://en.wikipedia.org/wiki/Mogensen%E2%80%93Scott_encoding) support for numbers and lists, as an alternative to Church encoding.

**Comment by ifrh** [comment]
In reply to https://github.com/chatziko/lci/issues/11#issue-1088652802
> It would be great to have a [Scott encoding](https://en.wikipedia.org/wiki/Mogensen%E2%80%93Scott_encoding) support for numbers and lists, as an alternative to Church encoding.

From what I see, there is support for Scott numbers, or am I missing something of your point?

https://github.com/chatziko/lci/blob/2deb0d4de73d109bd1f96bbf5ea67eee627df7ef/src/.lcirc#L117-L144

**Comment by suhr** [comment]
Oh, cool. Are lists also Scott encoded? Also, does it works for pretty-printing too?

**Comment by chatziko** [comment]
Scott-encoded numerals where in master for a while, I just made a new release that includes them. Pretty-print also works.

For lists there's no Scott-encoding in `.lcirc`, but `[a,b,c]` is just syntactic sugar for `a:b:c:Nil`, and `:`, `Nil` can be redefined, so any encoding can be added easily. Pretty-print wouldn't work though, I might add it in the future for Scott (or even try to add general algebraic data types).

So I'm closing this for now, feel free to reopen I you have a specific request.
