### ISSUE TITLE
Anyway to load from a file?

### ISSUE THREAD

**Issue by 4a594c** [chatziko/lci#15]
I have learned Lambda calculus, and I store my code (or equation) to a file, how can I load it? I have try and <

`lci < main.lc`

The code
```
'True' = (λx.λy.x)
'False' = (λx.λy.y)

'If' = (λb.λx.λy.b x y)

If True 0 1
```

**Comment by 4a594c** [comment]
Sorry, a update, I mean to open the file via command line not the repl

**Comment by chatziko** [comment]
There's no clean way, I marked this as enhancement.

But you can do the following as a hacky workaround:
```
echo "Consult 'main.lc'" | lci
```

**Comment by chatziko** [comment]
It's now possible in v1.1 to run `lci <file>`.
