### ISSUE TITLE
Using lambda (λ) sign leads to syntax error

### ISSUE THREAD

**Issue by leotaku** [chatziko/lci#2]
The documentation mentions that either a backslash or a greek lambda symbol can be used to denote a lambda expression. Using the later one, in my case, leads to a syntax error.

```
lci> (\ x -> x)

 \x.x
 (0 reductions, 0.00s CPU)
 ```

```
lci> (λ x -> x)
 Syntax error
```

**Comment by leotaku** [comment]
As a short look at the recent commit history reveals, this has been fixed after the last release. Sorry for the clutter.

**Comment by chatziko** [comment]
Indeed, before you needed the lambda in a greek encoding (iso-8859-7), now the lambda in utf8 should work.
